CREATE TABLE EVENTS (
  FIRSTNAME VARCHAR(60),
  LASTNAME VARCHAR(60),
  EMAIL VARCHAR(60),
  EVENT VARCHAR(60),
  NUMBER VARCHAR(60),
  CITY VARCHAR(60),
  GENDER VARCHAR(60),

PRIMARY KEY (EMAIl)
);